on: 
  push: 
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    - name: 🚚 Install Composer Dependencies SITE
      working-directory: ./
      run: composer install --prefer-dist
    
    - name: 🚚 Install Composer Dependencies ADM
      working-directory: ./public/adm
      run: composer install --prefer-dist
            
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.shopcuathuan.shop
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: |
          .git/**
          .git**
          .git*/**
          **/.git*
          **/.git*/**
          **/node_modules/**
          fileToExclude.txt
