name: Deploy to cPanel

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: 'cpanel'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Create Temporary Directory
        run: mkdir temp_deploy
      - name: Move Dist to Temporary Directory
        run: mv dist/* temp_deploy/
      - name: Upload to cPanel
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.4
  with:
    server: ftp.example.com
    username: ${{ secrets.FTP_USERNAME }}
    password: ${{ secrets.FTP_PASSWORD }}
    server-dir: /public_html
    local-dir: temp_deploy/
    exclude: .git*
      - name: Clean Up
        run: rm -rf temp_deploy
